# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 21:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CocktailComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='quantity of ingredient')),
                ('measure', models.CharField(choices=[('g', 'Grams'), ('ml', 'Millilitres'), ('pcs', 'Pieces')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='name')),
                ('liquid', models.BooleanField(default=True, verbose_name='is liquid')),
                ('abv', models.FloatField(default=0.0, verbose_name='alcohol by volume')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/ingredients/')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250, verbose_name='name')),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='img/recipes/', verbose_name='title image')),
                ('description', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(related_name='ingredients', to='recipes_adviser.CocktailComponent')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveSmallIntegerField(default=1)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='stages',
            field=models.ManyToManyField(related_name='stages', to='recipes_adviser.RecipeStage'),
        ),
        migrations.AddField(
            model_name='cocktailcomponent',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes_adviser.Ingredient'),
        ),
    ]
