# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_adviser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.CharField(default='lg', max_length=3, verbose_name='type of cocktail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, default='img/ingredients/default_ingredient.png', null=True, upload_to='img/ingredients/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title_image',
            field=models.ImageField(blank=True, default='img/recipes/default_recipe.png', null=True, upload_to='img/recipes/', verbose_name='title image'),
        ),
    ]
