# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_adviser', '0002_auto_20160318_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktailcomponent',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='cocktailcomponent',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cocktailcomponent',
            name='to_quantity',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='to quantity of ingredient'),
        ),
        migrations.AddField(
            model_name='cocktailcomponent',
            name='up_quantity',
            field=models.FloatField(default=30, verbose_name='up quantity of ingredient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(choices=[('g', 'Grams'), ('ml', 'Millilitres'), ('pcs', 'Pieces')], default='ml', max_length=3),
            preserve_default=False,
        ),
    ]
