# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_adviser', '0003_auto_20160318_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='components',
            field=models.ManyToManyField(related_name='recipes', to='recipes_adviser.CocktailComponent'),
        ),
        migrations.AlterField(
            model_name='cocktailcomponent',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='recipes_adviser.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='stages',
            field=models.ManyToManyField(related_name='recipes', to='recipes_adviser.RecipeStage'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('st', 'Shot'), ('lg', 'Long')], max_length=3, verbose_name='type of cocktail'),
        ),
    ]
