# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_adviser', '0004_auto_20160321_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='img/tools/default_tool.png', null=True, upload_to='img/tools/')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='tools',
            field=models.ManyToManyField(related_name='recipes', to='recipes_adviser.Tool'),
        ),
    ]
