# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_adviser', '0005_auto_20160330_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tool',
            new_name='CocktailTool',
        ),
    ]
